import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header, Navbar } from "@/components/common";
import GoogleAnalytic from "@/components/GoogleAnalytics/GoogleAnalytics";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prime Graphics",
  description: "Generated by create next app",
  other: {
    "google-site-verification": "e7B3G4vpyzjJI0hGemBMZoE0GcKs3oL5gZ1PJWGZH1o",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <meta name="google-site-verification" content="e7B3G4vpyzjJI0hGemBMZoE0GcKs3oL5gZ1PJWGZH1o" /> */}
        <Header />
        <GoogleAnalytic />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html >
  );
}
