export {default as EmbroideryPatch} from './EmbroideryPatch'
export {default as EmbroideryPatches} from './EmbroideryPatches'
export {default as LeatherPatch} from './LeatherPatch'
export {default as LeatherPatches} from './LeatherPatches'
export {default as PVCPatch} from './PVCPatch'
export {default as PVCPatches} from './PVCPatches'